TOOLTIPS = {
    "RESOLUTION_M": "Résolution du modèle d'élévation en mètres par pixel. Plus la valeur est basse, plus le relief est détaillé mais long à télécharger.",
    "SIZE_MM": "Taille maximale du modèle imprimé en millimètres, sur son plus grand côté.",
    "BASE_THICKNESS": "Épaisseur du socle sous le terrain, en unités du modèle.",
    "Z_SCALE": "Facteur d'exagération verticale du relief. 1.0 = échelle réelle, valeurs plus hautes accentuent les reliefs.",
    "ROAD_WIDTH_PX": "Largeur des routes dans le modèle, en pixels de la grille.",
    "ROAD_HEIGHT": "Hauteur de surélévation des routes au-dessus du terrain environnant.",
    "ROADS_Z_BOT_RATIO_PCT": "Détermine à quelle profondeur dans le socle la route est ancrée. 0% = fond du socle, 100% = surface du terrain.",
    "RIVER_WIDTH_PX": "Largeur des cours d'eau linéaires dans le modèle, en pixels de la grille.",
    "WATER_HEIGHT": "Hauteur de surélévation de l'eau au-dessus du terrain environnant.",
    "MIN_WATER_AREA_M2": "Surface minimale, en m², pour qu'un plan d'eau soit inclus dans le modèle.",
    "MIN_WATERWAY_LENGTH_M": "Longueur minimale, en mètres, pour qu'un cours d'eau soit inclus dans le modèle.",
    "WATER_Z_BOT_RATIO_PCT": "Détermine à quelle profondeur dans le socle l'eau est ancrée. 0% = fond du socle, 100% = surface du terrain.",
    "ENABLE_BATHYMETRY": "Active le suivi du relief sous-marin réel pour l'océan, à partir des données d'élévation.",
    "TREE_HEIGHT": "Hauteur des arbres générés dans les zones de végétation.",
    "TREE_RADIUS": "Rayon de la base des arbres générés.",
    "TREE_DENSITY": "Densité des arbres placés dans les zones de forêt, en nombre par unité de surface.",
    "VEG_Z_BOT_RATIO_PCT": "Détermine à quelle profondeur dans le socle la végétation est ancrée. 0% = fond du socle, 100% = surface du terrain.",
    "MIN_BUILDING_AREA_M2": "Surface minimale, en m², pour qu'un bâtiment soit inclus dans le modèle.",
    "DEFAULT_BUILDING_HEIGHT_M": "Hauteur par défaut utilisée quand un bâtiment n'a pas d'information de hauteur dans OpenStreetMap.",
    "METERS_PER_LEVEL": "Hauteur estimée d'un étage, utilisée pour calculer la hauteur des bâtiments à partir de leur nombre d'étages.",
    "BUILDING_HEIGHT_SCALE": "Facteur d'exagération de la hauteur des bâtiments dans le modèle imprimé.",
    "BUILDING_MIN_HEIGHT": "Hauteur minimale d'un bâtiment dans le modèle final, après mise à l'échelle.",
    "BUILDING_MAX_HEIGHT": "Hauteur maximale d'un bâtiment dans le modèle final, après mise à l'échelle.",
    "BUILDINGS_Z_BOT_RATIO_PCT": "Détermine à quelle profondeur dans le socle les bâtiments sont ancrés. 0% = fond du socle, 100% = surface du terrain.",
    "GPX_WIDTH_PX": "Largeur du tracé GPX dans le modèle, en pixels de la grille.",
    "GPX_HEIGHT": "Hauteur de surélévation du tracé GPX au-dessus du terrain environnant.",
    "GPX_Z_BOT_RATIO_PCT": "Détermine à quelle profondeur dans le socle le tracé GPX est ancré. 0% = fond du socle, 100% = surface du terrain.",
    "INCLUDE_RAILWAYS": "Inclut les voies ferrées dans la génération des routes, en plus du réseau routier classique.",
    "PUZZLE_N_PIECES": "Nombre de pièces du puzzle. 0 = désactivé. Le STL final sera découpé en N pièces avec tenons/mortaises pour assemblage physique.",
}